[build]
target = "x86_64-pc-windows-msvc"
rustflags = [
    "-C", "link-arg=/ENTRY:DriverEntry",
    "-Z", "pre-link-arg=/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.19041.0\\km\\x64"
]


